from markdown_it import MarkdownIt
from mdit_py_plugins.texmath import texmath_plugin
import re
import zlib
import base64

# Fix: Compile the massive regex once at module level to avoid recompiling on every call
DIAGRAM_RE = re.compile(
    r'```(mermaid|plantuml|d2|excalidraw|graphviz|structurizr)\s*\n(.{0,50000}?)\n```',
    flags=re.DOTALL
)

# Initialize the MarkdownIt parser
# We enable generic markdown features and HTML to allow rendering complex markdown.
md = (
    MarkdownIt('gfm-like', {'breaks': True, 'html': True})
    .use(texmath_plugin)
    .enable('table')
)

def convert(markdown_text: str) -> str:
    """
    Convert Markdown text to HTML using markdown-it-py.
    Processes math via texmath and Mermaid via mermaid.ink.
    """
    import urllib.parse
    
    # First, handle diagram blocks (mermaid, d2, plantuml) using Kroki API
    # because WeasyPrint/HTML won't render JS-based diagrams.
    def replace_diagram(match):
        diagram_type = match.group(1).strip()
        code = match.group(2).strip()
        import base64
        import zlib
        compressed = zlib.compress(code.encode('utf-8'), 9)
        encoded = base64.urlsafe_b64encode(compressed).decode('utf-8').rstrip('=')
        return f'<div style="text-align: center; margin: 1.5em 0;"><img src="https://kroki.io/{diagram_type}/png/{encoded}" class="diagram-{diagram_type}" style="max-width: 100%; object-fit: contain;"/></div>'

    # Fix: Placed a hard limit of 50,000 characters and call precompiled module-level regex
    markdown_text = DIAGRAM_RE.sub(replace_diagram, markdown_text)

    html = md.render(markdown_text)
    
    # Convert math strings generated by texmath to high-quality SVG images 
    # since WeasyPrint does not execute KaTeX JavaScript.
    def replace_inline_math(match):
        math_content = match.group(1).strip()
        encoded = urllib.parse.quote(math_content)
        return f'<img src="https://latex.codecogs.com/svg.image?{encoded}" style="vertical-align: middle; height: 1.25em;" alt="math" class="katex" />'
        
    def replace_block_math(match):
        math_content = match.group(1).strip()
        encoded = urllib.parse.quote(math_content)
        return f'<div class="katex-display" style="text-align: center; margin: 1.5em 0;"><img src="https://latex.codecogs.com/svg.image?{encoded}" style="max-width: 100%;" alt="math" /></div>'

    html = re.sub(r'<eq>(.*?)</eq>', replace_inline_math, html, flags=re.DOTALL)
    html = re.sub(r'<section><eqn>(.*?)</eqn></section>', replace_block_math, html, flags=re.DOTALL)
    
    return html
